---
Name: saltedherring
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SiteVersion:
  version: !!float 1
SilverStripe\View\SSViewer:
  themes:
    - 'default'
    - '$default'

Page:
  extensions:
    - SaltedHerring\Extensions\SocialDecorator
    - SaltedHerring\Extensions\PageDecorator
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SaltedHerring\Config\CustomSiteConfig
PageController:
  extensions:
    - SaltedHerring\Extensions\PageControllerDecorator
SilverStripe\Admin\ModelAdmin:
  extensions:
    - SaltedHerring\Extensions\ModelAdminExtension
SaltedHerring\Model\Project:
  extensions:
    - SaltedHerring\Extensions\ThumbnailDecorator
    - SaltedHerring\Extensions\MetaDecorator
SaltedHerring\Model\TeamMember:
  extensions:
    - SaltedHerring\Extensions\ThumbnailDecorator
    - SaltedHerring\Extensions\PublishedDecorator
    - SaltedHerring\Extensions\MetaDecorator
SaltedHerring\Model\AboutSection:
  extensions:
    - SaltedHerring\Extensions\MetaDecorator


SilverStripe\Assets\File:
  allowed_extensions:
    - swf
  force_resample: true

SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Image_Backend:
   properties:
     Quality: 90
  Intervention\Image\ImageManager:
    constructor:
      - { driver: imagick }

---
  Only:
    environment: 'live'
---
SilverStripe\Control\Director:
  alternate_base_url: 'https://www.saltedherring.com'
